### ISSUE TITLE
Unable to setup on Synology / Docker

### ISSUE THREAD

**Issue by timothe** [jorenn92/Maintainerr#890] opened 2024-02-10 18:19 UTC
**Describe the bug**
I wanted to give Maintainerr a try by setting it up on my Synology under DSM 7.2.1.
I can reach the portal however I see a redirect loop from the plex settings and only the sidebar is loading.

**To Reproduce**
1. Deploy the container
2. Navigate to http://[nasip]:6246/
3. I get redirected to http://[nasip]:6246/settings/plex

**Expected behavior**
I should be able to see and edit the settings to run the program.

**Logs**
Here's what I see in the logs:
```
...
[maintainerr] | 10/02/2024 18:12:34  [INFO] [RouterExplorer] Mapped {/api/collections/exclusions/:id/content/:page, GET} route
[maintainerr] | 10/02/2024 18:12:34  [INFO] [RouterExplorer] Mapped {/api/collections/logs/:id/content/:page, GET} route
[maintainerr] | 10/02/2024 18:12:34  [INFO] [SettingsService] Settings not found.. Creating initial settings
[maintainerr] | 10/02/2024 18:12:36  [INFO] [PlexApiService] Plex API isn't fully initialized, required settings aren't set
[maintainerr] | 10/02/2024 18:12:36  [WARN] [TasksService] An error occurred while creating the Collection Handler task. This is normal on first boot.
[maintainerr] | 10/02/2024 18:12:36  [INFO] [CollectionWorkerService] Creation of Collection Handler task failed. Retrying in 10s..
[maintainerr] | 10/02/2024 18:12:36  [INFO] [TasksService] Task Collection Log Cleaner created successfully
[maintainerr] | 10/02/2024 18:12:36  [WARN] [TasksService] An error occurred while creating the Rule Handler task. This is normal on first boot.
[maintainerr] | 10/02/2024 18:12:36  [INFO] [RuleExecutorService] Creation of Rule Handler task failed. Retrying in 10s..
[maintainerr] | 10/02/2024 18:12:36  [INFO] [TasksService] Task Rule Maintenance created successfully
[maintainerr] | 10/02/2024 18:12:36  [INFO] [NestApplication] Nest application successfully started
[maintainerr] | 10/02/2024 18:12:41  [WARN] [PlexApiService] Plex api communication failure.. Is the application running?
[maintainerr] | 10/02/2024 18:12:46  [INFO] [TasksService] Task Collection Handler created successfully
[maintainerr] | 10/02/2024 18:12:46  [INFO] [TasksService] Task Rule Handler created successfully
[maintainerr] | 10/02/2024 18:13:02  [WARN] [PlexApiService] Plex api communication failure.. Is the application running?
[maintainerr] | 10/02/2024 18:13:52  [WARN] [AppService] Couldn't fetch latest release version from GitHub
[maintainerr] | 10/02/2024 18:13:52  [WARN] [AppService] Couldn't fetch latest release version from GitHub
[maintainerr] | 10/02/2024 18:13:52  [WARN] [AppService] Couldn't fetch latest release version from GitHub
[maintainerr] | 10/02/2024 18:13:52  [WARN] [AppService] Couldn't fetch latest release version from GitHub
[maintainerr] | 10/02/2024 18:13:52  [WARN] [AppService] Couldn't fetch latest release version from GitHub
...
```

**Screenshot**
<img width="1333" alt="Screenshot 2024-02-10 at 18 17 17" src="https://github.com/jorenn92/Maintainerr/assets/6997555/c880622e-285c-4426-a76d-9214f754335f">

**Device (please complete the following information):**
 - OS: Synology / DSM 7.2.1
 - Version: ghcr.io/jorenn92/maintainerr:latest

**Additional context**
I tried:
* Changing network to bridge / host
* Deploying via docker compose / Portainer / DSM Container Manager

There's a user issue if I don't set the UID:GID up ("PLEASE UPDATE YOUR CONFIG..." message).
The WARN message only arises when I go to the website and get the infinite redirect behaviour.

**Comment by jorenn92** [comment] 2024-02-11 00:26
Duplicate of https://github.com/jorenn92/Maintainerr/issues/887

I'm not sure why this is happening, since nothing regarding the version changed. I'll look into it as soon as possible.
For now, using tag 2.0.0 should resolve it.

**Comment by jorenn92** [comment] 2024-02-11 00:50
Pushed a fixed and performed an emergency release. It should work with 2.0.2

**Closed** 2024-02-11 11:48 UTC

**Comment by timothe** [comment] 2024-02-11 12:08
![Surprised cat](https://i.chzbgr.com/full/9204612608/h339C1D32/cat)
What a quick turnaround! Thank you!

However I have another issue now. I re-created the container on the bridge network, which allowed me to connect to Plex without issue via localhost. However I can't connect to the other -arr instances. They run on Docker on the host network, and communicate perfectly between each other via localhost.

When on bridge network, I tried switching the url to:
* localhost
* [ip of the nas]
* host.docker.internal

Nothing worked. It doesn't connect.

So I switched the network from bridge to host for Maintainerr, but I can't get it to run. When I start it on host, I get this message in a loop:
```
 ⨯ Failed to start server
Error: getaddrinfo ENOTFOUND maintainerr
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'maintainerr'
}
```

I also tried to not define / define the hostname to different values, nothing fixed it.

Any idea?

**Comment by timothe** [comment] 2024-02-11 17:59
Actually, Plex' connection seemed to work before, but not anymore. Only authentication works.

**Comment by jorenn92** [comment] 2024-02-11 18:09
This seems like a general Nodejs error (https://github.com/nodejs/node/issues/44003#issuecomment-1196450595). I don't really know what's going on.. 

But, try to revert to the working config and prepend your hostname configurations with http(s)://. Also, make sure you're only using base_url when absolutely sure you need it.

The backend should automatically add http(s):// when it's not there, but i've had some recent reports that indicate it doesn't do that anymore..


> ![Surprised cat](https://camo.githubusercontent.com/2d439815592431c257c942e416909f55f9d27dbb697a57aea7e75197b48e60b0/68747470733a2f2f692e63687a6267722e636f6d2f66756c6c2f393230343631323630382f6833333943314433322f636174) What a quick turnaround! Thank you!
> 
> However I have another issue now. I re-created the container on the bridge network, which allowed me to connect to Plex without issue via localhost. However I can't connect to the other -arr instances. They run on Docker on the host network, and communicate perfectly between each other via localhost.
> 
> When on bridge network, I tried switching the url to:
> 
>     * localhost
> 
>     * [ip of the nas]
> 
>     * host.docker.internal
> 
> 
> Nothing worked. It doesn't connect.
> 
> So I switched the network from bridge to host for Maintainerr, but I can't get it to run. When I start it on host, I get this message in a loop:
> 
> ```
>  ⨯ Failed to start server
> Error: getaddrinfo ENOTFOUND maintainerr
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
>   errno: -3008,
>   code: 'ENOTFOUND',
>   syscall: 'getaddrinfo',
>   hostname: 'maintainerr'
> }
> ```
> 
> I also tried to not define / define the hostname to different values, nothing fixed it.
> 
> Any idea?

**Comment by jorenn92** [comment] 2024-02-11 18:09
> Actually, Plex' connection seemed to work before, but not anymore. Only authentication works.

You can't communicate with Plex anymore?

**Comment by timothe** [comment] 2024-02-11 18:42
Ok it gets weirder.

I'm running on the bridge network.

Re: Plex, authentication is done so it gets me a list of servers to connect to when I click the 🔁 button. I have only one server but I get 2 pairs of config, either hostname or IP, local or remote. So my list is:
* manual config
* hostname - local
* hostname - remote
* ip - local
* ip - remote
However, no matter what choice I make, it doesn't reach Plex: `Connection failed! Please check and save your settings`

It's weird because I run 15 containers daily alongside a VM and other apps on this NAS. Some are exposed on the local network, others on the internet, or some are not. But it's the first time I have this issue.

Usually I solve this by using the host network, but with this config, I get the network error I mentioned before and the app is not running.

I tried this:
* Using bridge, I removed all files in data to try a new setup. Once authenticated with Plex, I go back to the same issue described above, with: `   - Local:        http://maintainerr:6246
[maintainerr] | 11/02/2024 18:21:41  [WARN] [PlexApiService] Plex api communication failure.. Is the application running?`
* I recreated the container using host, again with a clean slate, and got it again with:
``` ⨯ Failed to start server
Error: getaddrinfo ENOTFOUND maintainerr
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'maintainerr'
}
```
* So I looked online to check similar issues with node & Docker, which make me came back to your point about urls
* I came back and tried putting `http://[local nas ip]` for every service and... it WORKED!

I know it's quite explicit as it's marked _Test Saved_ but the test only works AFTER you click save and it feels _weird_.

Thank you for your app and support, super duper appreciated! 🙏 
I'm running to try it out now 🏃

**Comment by MichaelGoedken** [comment] 2024-04-22 00:37
Exact same issue is happening with me except I cannot get it to work at all on bridge mode.
